### ISSUE TITLE
Version badge

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#10]
For letting others know which is the gem's version, we want to use a version badge

**Comment by roman-dubrovsky** [comment]
P.S. maybe we should release this gem before adding the version badge

**Comment by AleksSenkou** [comment]
@roman-dubrovsky for testing it or what the reason?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I don't really clear your question

**Comment by AleksSenkou** [comment]
@roman-dubrovsky the reason for releasing gem before adding version badge isn't clear to me

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I'm just thinking that we need to sign up to ruby gems and release the gem before getting access to version badge

**Comment by roman-dubrovsky** [comment]
like a badge for CircleCI (we're set up CircleCi before getting the CircleCI badge)

**Comment by roman-dubrovsky** [comment]
@AleksSenkou does it make sense?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky yeah, it makes sense 👍
