### ISSUE TITLE
RSpec/ExampleLength cop value 

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#114]
Do you have any thoughts about should we increase this value to 8 or 10. (Default value is 5)

E.g. we have the next example

```ruby
        it 'creates correct deal config object' do
          expect(ZohoUtil::DealConfig).to receive(:new)
            .with(
              deal_name: translated_deal_name,
              stage_uid: zoho_post.stage_uid,
              change_existing_stage: zoho_post.change_existing_stage,
              note_title: translated_note_title,
              note: translated_note
            )

          execute_action
        end
```

should we leave it as here? or move arguments into let variable? 

```ruby
        let(:service_arguments) do
          {
            deal_name: translated_deal_name,
            stage_uid: zoho_post.stage_uid,
            change_existing_stage: zoho_post.change_existing_stage,
            note_title: translated_note_title,
            note: translated_note
          }
        end

        it 'creates correct deal config object' do
          expect(ZohoUtil::DealConfig).to receive(:new).with(**service_arguments)
          execute_action
        end
```

Also, we have an option just to turn off that cop (and check that each test should have only one expectation block). 

What do you think?

**Comment by texpert** [comment]
I'd certainly move the arguments to let variable, and increase the example length to 10.

**Comment by roman-dubrovsky** [comment]
@texpert would you like to make both changes 🤔 ?

**Comment by texpert** [comment]
Maybe next week, if it could wait. I'm still at my old job.

**Comment by roman-dubrovsky** [comment]
no, it's 10 mins changes and I'll add it my own this weekend. I meant your idea. Do you want to see increasing that metric to 10 in config but that particular case you prefer to refactor and move arguments to `let` block?

**Comment by texpert** [comment]
OK

"Do you want to see increasing that metric to 10 in config but that particular case you prefer to refactor and move arguments to let block?" - exactly!

**Comment by TheBlackArroVV** [comment]
I believe, that it's better to live it without `let` in that way code is easier

**Comment by texpert** [comment]
Using let assures the data wouldn't leak across other examples. Otherwise, there will be chances of flaky spec failures.
