### ISSUE TITLE
Don't use `should` in the Rspec tests 

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#117]
**Is your feature request related to a problem? Please describe.**

On the our project, we have some legacy tests which have been written via `should` methods. 
New tests we're writing via `expect` syntax. And now we have some fix of syntaxes but going to change it. But the main issue that default rubocop config does not handle that case. 

So for that issue:

* [ ] find the needed cop in the rubocop documentation. (I believe that this cop presents)
* [ ] setup it for our Rspec config 

**Additional context.**
About `expect` syntax usege - http://www.betterspecs.org/#expect

**Comment by texpert** [comment]
AFAIK, rubocop has no such cop, should be refactored by hand.

**Comment by roman-dubrovsky** [comment]
😞

**Comment by roman-dubrovsky** [comment]
looks like that won't add that cop cause Rspec configuration has already had that feature https://github.com/rubocop-hq/rubocop-rspec/issues/587 

But would you like to have that cop? Especially if we have many `should` syntax tests and need to move to `expect` syntax step-by-step?

**Comment by texpert** [comment]
I think the development of such a cop isn't worth the effort. The refactoring is gonna be needed once, and only for the apps which are using the very old `should` syntax. The detecting cop is enough, as for me.

**Comment by roman-dubrovsky** [comment]
Ok, as a result, RubocopRspec doesn't have and won't develop that cops cause we have that feature in the Rspec Core library. Instead of that, they suggest to set up your tests correctly and have a special block for that (see https://github.com/rubocop-hq/rubocop-rspec#enforcing-should-vs-expect-syntax ) 


So my question: how do you think which approach is better for us?

👀 - agreed with them and add to our README section to their guide about setting up RSpecs
🚀 - develop custom cop and use it in our project. But looks like these cops won't be merged to original Rspec Rubocop gem.

**Comment by texpert** [comment]
I think the 1st option is good enough if accomplished by the correct setup. 

Better than writing a cop, I'd suggest to implement some kind of generator to add this into the RSpec config, if RSpec is installed and expectation.syntax is not configured - https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#disable-should-syntax

**Comment by roman-dubrovsky** [comment]
@texpert got it and agree with you. But about RSpec config generator, I don't want to add it to this library (@dzhlobo wanted to make library for generating empty for Rails app with all configured files and env. like https://github.com/thoughtbot/suspenders. And probably this case for that library). So I just add a note to Readme
