### ISSUE TITLE
Prevent writing duplication tests and contexts

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#122]
<img width="978" alt="Screen Shot 2019-11-04 at 11 57 01 PM" src="https://user-images.githubusercontent.com/7738063/68157562-f097ce00-ff5e-11e9-920f-2225e8f02279.png">

**Comment by lazycoder9** [comment]
@roman-dubrovsky Made some investigation and tried to setup these cops [RSpec/RepeatedDescription](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecrepeateddescription) and [RSpec/RepeatedExample](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecrepeatedexample). These cops are good, but they are not preventing/detecting context/describe level duplication. Also, there are no issues/cop ideas in rubocop-rspec repo. Maybe we can create it by ourselves?

**Comment by roman-dubrovsky** [comment]
@lazycoder9 👍 added label `blocked`

**Comment by nikitasakov** [comment]
Update: PR with cops merged to rubocop-rspec. I think we should wait for new release and when it updated we can close this issue.
