### ISSUE TITLE
Fix changelog entries to simple past tenses

### ISSUE THREAD

**Issue by texpert** [datarockets/datarockets-style#123]
`Disable` is imperative. The changelog is about what has been done, not about what should be done, so better to put it in the past: 'DisableD`

**Comment by roman-dubrovsky** [comment]
Any thoughts?

Personally, I don't have any strong objections. I just prefer to use present simple tense cause this is the most usual approach for writing Changelog.

**Comment by AleksSenkou** [comment]
Are there any community practices on how to build changelogs? I'm ok with both present and past tenses

**Comment by roman-dubrovsky** [comment]
@AleksSenkou no practices. All maintainers do it as they want (but I could find gems only with present tense or w/o convention) 

present tense - https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md
present tense - https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md
present tense - https://github.com/plataformatec/devise/blob/master/CHANGELOG.md
present tense - https://github.com/plataformatec/simple_form/blob/master/CHANGELOG.md
just no rules (add near with adds) - https://github.com/rspec/rspec-rails/blob/master/Changelog.md
just no rules - https://github.com/faker-ruby/faker/blob/master/CHANGELOG.md

**Comment by roman-dubrovsky** [comment]
But we have the issue that our labels use past tense but notes use present

**Comment by AleksSenkou** [comment]
Looks like nothing should be changed in changelog file then

**Comment by AleksSenkou** [comment]
> But we have the issue that our labels use past tense but notes use present

@roman-dubrovsky which labels do you mean? Github labels in this repo have present tense, they are mostly adjectives

**Comment by nikitasakov** [comment]
Tried to find some rules and found this resource - https://keepachangelog.com/en/1.0.0/. Our CHANGELOG has almost the same structure with labels in past simple and notes in present. It seems to me that we can leave CHANGELOG without changes.

**Comment by nikitasakov** [comment]
@AleksSenkou I would venture to suggest that Roma meant labels kinda `Added`, `Changed` etc in our CHANGELOG

**Comment by AleksSenkou** [comment]
> tried to find some rules and found this resource - https://keepachangelog.com/en/1.0.0/.

@nikitasakov agreed to leave changelog as it 👍 
It's really nice and easy-readable

**Comment by nikitasakov** [comment]
So we can close this issue or there are other opinions?

**Comment by AleksSenkou** [comment]
@nikitasakov guess we can close it
