### ISSUE TITLE
Thing about development dependencies and removing Gemfile.lock

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#124]
See https://github.com/datarockets/datarockets-style/pull/119#discussion_r342550405

**Comment by roman-dubrovsky** [comment]
I just print a wrong issue id to commit. Should be #126

**Comment by nikitasakov** [comment]
BTW, In addition to the discussion, I've read https://bundler.io/v2.0/guides/creating_gem.html and found this:
```
Gemfile: Used to manage gem dependencies for our library’s development. 
This file contains a gemspec line meaning that Bundler will include dependencies specified 
in foodie.gemspec too.
It’s best practice to specify all the gems that our library depends on in the gemspec.
```

**Comment by roman-dubrovsky** [comment]
seems like dependabot has been broker after removing `Gemfile.lock`. So we can't handle our dependencies automatically. So my proposal is to return `Gemfile.lock` to the project. ANy thoughts?  cc @nikitasakov @paydaylight

**Comment by roman-dubrovsky** [comment]
cc @texpert

**Comment by texpert** [comment]
> seems like dependabot has been broker after removing `Gemfile.lock`. So we can't handle our dependencies automatically. So my proposal is to return `Gemfile.lock` to the project. ANy thoughts? cc @nikitasakov @paydaylight

What was the issue with Dependabot?

**Comment by paydaylight** [comment]
@texpert apparently it can't update a dependency without Gemfile.lock. We discussed with @roman-dubrovsky that making dependencies strict in gemspec may solve this issue.

**Comment by texpert** [comment]
> @texpert apparently it can't update a dependency without Gemfile.lock. We discussed with @roman-dubrovsky that making dependencies strict in gemspec may solve this issue.

Hm, what's the error? I have just installed Dependabot on my gem, and it has successfully created the PR - https://github.com/texpert/shrine-lambda/pull/17
