### ISSUE TITLE
Fix Rspec configuration

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#129]
Fix RSpec configuration via Rspec linting configs

See #117

**Comment by nikitasakov** [comment]
Could you please clarify what exactly should be fixed?

In #117 I see that we decided not to go with cop but add to our README section about setting up RSpecs. It added here https://github.com/datarockets/datarockets-style/commit/47349c10c6f9ee81dc56b4b65919eee45cea678d

This link goes to https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#disable-should-syntax And as I see it already added https://github.com/datarockets/datarockets-style/blob/master/spec/spec_helper.rb#L11

It is just a bit unclear what to fix

**Comment by roman-dubrovsky** [comment]
@nikitasakov np, I'll fix it myself

**Comment by roman-dubrovsky** [comment]
@nikitasakov it was about fixing configuration for current Rspec config (which we're using for testing cops) .

**Comment by roman-dubrovsky** [comment]
and looks like it has been done
