### ISSUE TITLE
Setup Layout/ArrayAlignment cop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#130]
Setup [the next cop](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutarrayalignment). 

By default, it orders by the first line arguments 

```ruby
  method_object %i[steps_data! start_step! checks_data! actions_data! waits_data! notes_data!
                   connections_data! timezone! workflow!]
```

but it should be a fixed indentation level

```ruby
  method_object %i[steps_data! start_step! checks_data! actions_data! waits_data! notes_data!
    connections_data! timezone! workflow!]
``` 

We discussed it before and made the same for other cops. See  https://github.com/datarockets/datarockets-style/blob/master/doc/STYLE_GUIDE.md#style-parameters-aligning

P.S.  In the current 0.76.0 version this cop is `Layout/AlignArray`, but in the master, this cop is `Layout/ArrayAlignment` and probably will be changed in the next release

**Comment by lazycoder9** [comment]
@roman-dubrovsky Should we bump rubocop's version in 0.7.0 milestone?

**Comment by roman-dubrovsky** [comment]
yep, sure

**Comment by lazycoder9** [comment]
@roman-dubrovsky I've tried to just turn off this cop (there are no other options) to not autocorrect indentation. The result is that I can write multiline arrays as I wish and there will be no warnings or proper autocorrections even if indentation is awful, like this
```ruby
        some_var = %i[elem1
elem2
  elem3
                        elem4]
```
Here is a proof
![image](https://user-images.githubusercontent.com/19951609/71714663-9321df80-2e30-11ea-8f76-104ae7f005e8.png)
_(blue warning is just for unused var)_

**Comment by nikitasakov** [comment]
So looks like we should implement our own cop. Will work on it
