### ISSUE TITLE
Usage of rubocop 0.77.0 version causes errors

### ISSUE THREAD

**Issue by DDKatch** [datarockets/datarockets-style#137]
Latest `rubocop` release [0.77.0](https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0) has broken changes, so this gem doesn't work:
<img width="859" alt="Screen Shot 2019-12-05 at 4 36 31 PM" src="https://user-images.githubusercontent.com/14095146/70241006-530f0480-177f-11ea-9787-ebe4713b6341.png">

To-Do list:

- [x] set `rubocop` gem version to _0.76.0_ or update the config mentioned in error message

**Comment by roman-dubrovsky** [comment]
Just update rubocop version (PR https://github.com/datarockets/datarockets-style/pull/135) and fix all conflicts (rubocop provides a good description for that issues)

**Comment by DDKatch** [comment]
Ok, will do shortly
