### ISSUE TITLE
Add some topics to repo

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#15]
See https://help.github.com/en/articles/about-topics

**Comment by AleksSenkou** [comment]
Sounds good to me 👍

**Comment by AleksSenkou** [comment]
Thoughts about:

`ruby`, `rubocop`, `linter`, `patch`

?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou why `patch`?

**Comment by roman-dubrovsky** [comment]
> ruby, rubocop, linter

**Comment by AleksSenkou** [comment]
@roman-dubrovsky cause I'd like to show that this repo has inherited rubocop's

**Comment by AleksSenkou** [comment]
Done ✅
