### ISSUE TITLE
Disable RSpec/DescribeClass for request tests

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#152]
**Is your feature request related to a problem? Please describe.**

The main idea of that cop, that we should name top-level describe block via class name which we're going to test. See [link](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecdescribeclass).

It works nice for unit tests, but it does not work for request and, probably, feature or capybara test. 

```ruby
describe "Authentication API V1" do
end
```

So my proposal is disabling this cop for `spec/request` directory (other directories we can add later).

**Comment by lazycoder9** [comment]
@roman-dubrovsky BTW, what do you think about using controller class in such kind of specs?
```ruby
describe API::SessionController do
    # ...
end
```

**Comment by nikitasakov** [comment]
Why not just specifying `type` in this case? Like [here](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec#requesting-a-json-response) for example. It is legal:
```ruby
describe "Authentication API V1", type: :request do
end
```

**Comment by roman-dubrovsky** [comment]
@nikitasakov  heh, funny. I missed that you can set `type` instead of class. 

Looks like we can close this issue but for me, all solution looks like hacks:

1) @lazycoder9 looks like a hack only for request tests and we can't apply the rule e.g. for capybara tests

2) @nikitasakov solution looks like the most legal but here we lose RSpec feature to detect test type by directory name and just should set up `type` each time. 

3) adding excluding to cop is also a hack. 

So what do you think about that issue?

**Comment by roman-dubrovsky** [comment]
ok, I close this issue and the default solution is setting `type` manually, but the real solution should be discussed in the project. Does it make sense?
