### ISSUE TITLE
Style/ClassAndModuleChildren

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#19]
I prefer to use the Rails compact style but looks like there are some issues with it.

```
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
```

https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassandmodulechildren
https://github.com/rubocop-hq/ruby-style-guide#namespace-definition

**Comment by AleksSenkou** [comment]
@roman-dubrovsky sorry, I can't understand it. Can you please give more details?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou this cop about writing this code

```ruby
# compact style
class Users::CreateUser
```

instead of this one

```ruby
# nested style
module Users
  class CreateUser
  end
end
```

Just guys suggest not to use the compact style for any reasons. So will be great to investigate this issue and understand in which cases we should use nested style, in which compact

**Comment by AleksSenkou** [comment]
@roman-dubrovsky got it. I had an issue with compact style once or twice. Kind of exception from the rule 😄 Can't remember what was the issue

**Comment by DDKatch** [comment]
@AleksSenkou , @roman-dubrovsky I agree 100% not to use the compact style. And there my reasons:
**1. You can't use classes from the same namespace freely.**
For example:
_keks/build.rb_
```
class Keks::Build
    def call
        Keks::Fetch.call
        Keks::Save.call
    end
end
```

_keks/fetch.rb_
```
class Keks::Fetch
    def call
       # fetch
    end
end
```

_keks/save.rb_
```
class Keks::Save
    def call
       # save
    end
end
```

Overall looks ok. But. What if we have outer namespace here, `AmaizingAndUnbellievableAndSuperDuperCool` for example?
Look what will happen with `Build` class:

```
class AmaizingAndUnbellievableAndSuperDuperCool::Keks::Build
    def call
        AmaizingAndUnbellievableAndSuperDuperCool::Keks::Fetch.call
        AmaizingAndUnbellievableAndSuperDuperCool::Keks::Save.call
    end
end
```
Still easy to read? ok. What if we need to enchance our `Fetch` class so we'd like to use inheritance. Look what will happen:
_keks/enchanced_fetch.rb_
```
class AmaizingAndUnbellievableAndSuperDuperCool::Keks::EnchancedFetch < AmaizingAndUnbellievableAndSuperDuperCool::Keks::Fetch
    def call
       # enchanced fetch
    end
end
```

120 symbols in line they said. However the main point there is instead just `EnchancedFetch < Fetch` we need to write, read and understand the whole line where 90% have no meaning for us at all, at the exact moment.

**I think this style of code is totally not ok.**
There are also another cases with combination of services, but I think you've already grasp the main idea)

**Comment by AleksSenkou** [comment]
Some points for using `compact` style:

1) We don't need to use nested style for controllers, especially for easy written:
```ruby
class V1::Users::PostsController < ApplicationController
```

Do we really need? It plays bad joke with code readability, doesn't it?
```ruby
module V1
  module Users
    class PostsController < ApplicationController
    end
  end
end
```

2) Imagine you had compact style to have prettier code looking
Keks::Fetcher and Keks::Builder
```ruby
module Keks
  class Builder
    def call
        Fetcher.call
    end
  end
end
```

then you found out that Fetcher shouldn't be really in Keks namespace, but Another namespace, so you have:

```ruby
module Keks
  class Builder
    def call
        Another::Fetcher.call
    end
  end
end
```
Compact doesn't make much sense, isn't it? So you change it to nested, pretty energy-taking behavior

Better:
```ruby
class Keks::Builder
  def call
    Another::Fetcher.call
  end
end
```

----------------------------------------------------------

Such edge cases as 
```ruby
class AmaizingAndUnbellievableAndSuperDuperCool::Keks::EnchancedFetch < AmaizingAndUnbellievableAndSuperDuperCool::Keks::Fetch
```

really can be handled with compact style

----------------------------------------------------------

At the end of the day, I'd like to have compact when it really helps but nested in all other points. The thing is that rubocop can't provide such configuration [docs](https://rubocop.readthedocs.io/en/stable/cops_style/#styleclassandmodulechildren)

Having our own agreement to have both will lead that we'll have either nested or compact where it's not needed (somebody forgot to change + missed during the review)

If we can make changes to the cop for having 3-d option -> would be great

Until that going with one of them (compact or nested without exceptions) makes the most sense to me

------------------------------------------------------------

Thoughts?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou 

1) yeap, but usually we should not have the next controllers schema

```ruby
class V1::Users::PostsController < ApplicationController
```

- when we implement an additional base controller for each version which should implement some specific versions things for the current version (method of authorization, some exception handlers and e.g.) 

```ruby
class V1::BaseController < ApplicationController
end

class  V1::Users::PostsController  < V1::BaseController
```

- when we wrap some controller into `Users` module it usually means that we have a route like `users/:user_id/posts` and e.g.

so for me, making a base controller for Users module is a good idea so that we can isolate uniq logic for finding and authorizing users. 

```ruby
class V1::Users::BaseController < V1::BaseController
end

class  V1::Users::PostsController  < V1::Users::BaseController
```

- in the example above, we can have a lot of versions and a lot of Users modules and we don't want to duplicate `Users::BaseController` logic each time. So here, I prefer to move shared `Users::BaseController` logic into module and make multi-inheritance for `Users::BaseController`  controllers but I prefer to still use base controllers for each versions so that we can override some logic for some specific version
 
```ruby
class V1::BaseController < ApplicationController
end

class V1::Users::BaseController < V1::BaseController
  include UsersFindable
end

class  V1::Users::PostsController  < V1::Users::BaseController
end

class V2::BaseController < ApplicationController
end

class V2::Users::BaseController < V2::BaseController
  include UsersFindable
end

class  V2::Users::PostsController  < V2::Users::BaseController
end
```

And here looks like `nested` style makes sense.  Thoughts?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky 
1) is excellent manual on how to organize versioning 👍 
2) it's about changing namespace of service, it was `Keks::Fetcher` but ended up using `Another::Fetcher`

**Comment by roman-dubrovsky** [comment]
@AleksSenkou 

2. yep, I just don't understand your pain here

**Comment by roman-dubrovsky** [comment]
> 1. is excellent manual on how to organize versioning 👍

@AleksSenkou for me, this is the best approach for organizing versioning via Rails controllers. But I don't like it and won't work for cases when we work with mobile apps and can make a new version each month.

**Comment by nikitasakov** [comment]
I've read a bit about it and here is a result:

First of all I understood that those 2 syntaxes are not the same. The difference is in constants and their scope. (https://stackoverflow.com/a/24393133, https://stackoverflow.com/a/48944664). 

Kinda this behavior in ruby:
```
module A
  MARCO = "polo"
  module B
    def self.n 
      puts Module.nesting.inspect  # => [A::B, A]
      puts MARCO # => "polo"
    end
  end
end
```
```
module A
  MARCO = "polo"
end

module A::B
  def self.n 
    puts Module.nesting.inspect  # => [A::B]
    puts MARCO # => uninitialized constant A::B::MARCO (NameError)
  end
end
```
>It turns out that the "inheritance" of a parent's constants by the child isn't due to the parent/child relationship. It's lexical.

And this behavior is true for Ruby, **but not for Rails**. It is because of Rails autoloading. 

```
# a.rb
module A
  MARCO = "polo"
end

# a/b.rb
module A::B
  def self.n 
    puts MARCO # => "polo"
  end
end

# some_controller.rb
A::B.n()
```

>This is possible because Rails implements an autoload system. It uses Module.const_missing to detect when you try to reference a constant that hasn't been loaded. It then loads the files it believes should contain the constant. This works most of the time, but there's a catch.

**Important:**

>Rails assumes that a module always has the largest possible nesting. It assumes that module A::B::C will have a nesting of [A::B::C, A::B, A]. If it doesn't you'll get unexpected behavior.

So you should think about it if you use compact syntax.

I have no personal preferences but according resources which I found - nested syntax is more preferred because of unobvious behavior of compact syntax in some cases.

**Read:**
https://www.honeybadger.io/blog/avoid-these-traps-when-nesting-ruby-modules/

**Comment by texpert** [comment]
Another good article explaining issues of shortcut syntax - https://randycoulman.com/blog/2014/12/09/namespaced-classes-in-rails/

**Comment by DDKatch** [comment]
Looks like me, @roman-dubrovsky, @nikitasakov, @texpert  want to use nested syntax due to experienced disadvantages and the only @AleksSenkou wants to use the short syntax so far.
Let's use the nested syntax (which is a default BTW) and close this issue

**Comment by roman-dubrovsky** [comment]
@AleksSenkou Do you have any objections?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky no objections, thank you

**Comment by atatarenko** [comment]
Just my two cents, the shortcut syntax feels like something too Rails specific. I mean, there is no question considered for the preferred syntax outside the Rails world. If we take a look at any Ruby gem setup it will be obvious that the nested syntax is the only option. Even in Rails, it's highly recommended to not use shortcuts so that some parts could be pulled out to gems at some point in time.

+1 for having nested syntax cop as default.
