### ISSUE TITLE
Discuss and setting up Style/HashAsLastArrayItem cop 

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#199]
**Is your feature request related to a problem? Please describe.**
Here I just want to discuss rule for [this cop](https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem). 

This cop sets up a rule for hash braces in the array.

**EnforcedStyle: braces (default)**

```ruby
# bad
[1, 2, one: 1, two: 2]

# good
[1, 2, { one: 1, two: 2 }]
```

**EnforcedStyle: no_braces (our rule)**

```ruby
# bad
[1, 2, { one: 1, two: 2 }]

# good
[1, 2, one: 1, two: 2]
```

cons of each rule on real examples:

For `braces` rule

In the `include` blocks we need to add hash braces 

```ruby
Post.unscoped.includes({account_holders: [{user: :profile}]})
```

Usually, I write something like this 

```ruby
Post.unscoped.includes(account_holders: [user: :profile])
```

For `no_braces` rule, usually, I faced the issue on creating an expected response for any API

Instead of writing some array which contains list of object

```ruby
let(:contacts_list) do
  {
    contacts: [{contactID: 'test'}]
  }
end
``` 

I need to write this variant 

```ruby
let(:contacts_list) do
  {
    contacts: [contactID: 'test']
  }
end
```

But if says a truth it can be really easy refactored

```ruby
let(:contact) { {contactID: 'test'}  }
let(:contacts_list) { {contacts: [contact] } }
```

What do you think about it?

**Comment by roman-dubrovsky** [comment]
P.S. Also right now `no_braces` has a bug for array of hashes. It converts this expression 

```ruby
contacts = [{contactID: 'test'}, {contactID: 'test2'}]
```

to this one 

```ruby
contacts = [contactID: 'test', contactID: 'test2']
```

which is equal `[{:contactID=>"test2"}]` 

But I'm going to report this issue to rubocop library

**Comment by roman-dubrovsky** [comment]
Personally, I still love `no_braces` rule more

**Comment by texpert** [comment]
I'm also for `no_braces`.

**Comment by DDKatch** [comment]
`[1, 2, one: 1, two: 2]` may mislead to think that the real value here is `[1, 2, {one: 1}, {two: 2}]` but actually `[1, 2, {one: 1, two: 2}]`. It may lead to mistakes.

**Comment by DDKatch** [comment]
`[contactID: 'test']` convertes to `[{:contactID=>"test2"}]`. I always thought it's how ruby works 🤔 
The issue(https://github.com/rubocop-hq/rubocop/issues/8323) was about parsing errors for a multiline array of hashes

**Comment by roman-dubrovsky** [comment]
> [1, 2, one: 1, two: 2] may mislead to think that the real value here is [1, 2, {one: 1}, {two: 2}] but actually [1, 2, {one: 1, two: 2}]. It may lead to mistakes.

@DDKatch are you sure? in you case, you should write something like this (by this cop) `[1, 2, {one: 1}, two: 2]`. It looks suck but it's easy for refactoring or we can patch this rubocop rule in the future (e.g. restrict this rule for multiple array) 

> [contactID: 'test'] convertes to [{:contactID=>"test2"}]. I always thought it's how ruby works 🤔
The issue(rubocop-hq/rubocop#8323) was about parsing errors for a multiline array of hashes

in my example above, ruby just overrides the value for  `contactID` key

**Comment by roman-dubrovsky** [comment]
this issue has been fixed https://github.com/datarockets/datarockets-style/issues/199#issuecomment-660365177 

from documentation: 

```ruby
# good
[{ one: 1 }, { two: 2 }]
```

So I'm going to close this issue and leave `no_braces` style
