### ISSUE TITLE
Configure Style/TrailingCommaInHashLiteral cop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#218]
I'd like to change the default value for `EnforcedStyleForMultiline ` for [this cop](https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainhashliteral). 

By default, this is `no_comma` and we remove last coman for multiline hash

```ruby
test = {
  a: 1,
  b: 2,
  c: 3
}
```

By proposal, it using `consistent_comma` rule which is same approach which we use for our JS lintes (it adds a comma for last hash element)

```ruby
test = {
  a: 1,
  b: 2,
  c: 3,
}
```

Do you have any thoughts?

**Comment by texpert** [comment]
I'd love to stick with removing the last comma.

**Comment by roman-dubrovsky** [comment]
Let's continue with new `consistent_comma`: 6 votes vs 4 votes

<img width="1597" alt="Screen Shot 2020-11-10 at 18 14 14" src="https://user-images.githubusercontent.com/7738063/98693074-e03fdd80-2380-11eb-901d-1bcfbf600b95.png">

@texpert do you have any strong objections?

**Comment by roman-dubrovsky** [comment]
also we have the same result in the DeakMaker team 😄 

<img width="965" alt="Screen Shot 2020-11-10 at 18 20 39" src="https://user-images.githubusercontent.com/7738063/98693616-8e4b8780-2381-11eb-934e-a43eaf4cc721.png">

**Comment by texpert** [comment]
It is OK for me, @roman-dubrovsky :)
