### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#220]
**Is your feature request related to a problem? Please describe.**
After updating rubocop to `1.*.*`, get the next warnings

```
config/base.yml: Layout/ArrayAlignmentExtended has the wrong namespace - should be Cop/Layout
config/base.yml: Style/NestedInterpolation has the wrong namespace - should be Cop/Style
```

**Comment by roman-dubrovsky** [comment]
This happens because of these changes https://github.com/rubocop-hq/rubocop/pull/8490 

So this cop has the next class name `Datarockets::Style::Cop::Style::NestedInterpolation`, rubocop cut two first module and wants that name was `Cop/Style/NestedInterpolation`. 

So easier way here, try to change modules `Datarockets::Style` to `DatarocketsStyle`. Also, we can try to path original logic, But I don't really want to do it. Do you have any thoughts?

**Comment by texpert** [comment]
Yeah, it seems easier and better to change our namespace.
