### ISSUE TITLE
Make note in the forum (so that other teams start using it)

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#25]
The team should be notified about internal linters we use

**Comment by AleksSenkou** [comment]
@roman-dubrovsky do you have specific notes that you would like to share on the forum?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I don't. Maybe just let's use and contribute it

**Comment by roman-dubrovsky** [comment]
@AleksSenkou any updates?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky nope. I don't have an Idea how to write about it with value

**Comment by roman-dubrovsky** [comment]
@AleksSenkou do you need any help here?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I guess I need good idea 😄 

Topic can be: `Linters`
Can include examples of our custom linters for rubocop and eslint

**Comment by roman-dubrovsky** [comment]
> Can include examples of our custom linters for rubocop and eslint

@AleksSenkou what do you mean on it?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I'd like to have topic informative. Let me create it and ask you for the review 😃

**Comment by nikitasakov** [comment]
@AleksSenkou Are you going to work on it? Do you have any ideas?

**Comment by AleksSenkou** [comment]
@nikitasakov I am not about to work on it, 
the idea is simple - mention that we have this gem somewhere in dev practices description

**Comment by roman-dubrovsky** [comment]
@nikitasakov can you leave some information in the forum:

1) like we have a repo with ruby style guide
2) short info with documentaion for style guide
3) link to doc how to set up it
4) link to doc how to contribute 
5) maybe something else for your taste

**Comment by nikitasakov** [comment]
@roman-dubrovsky Will work on it right now. Can you please clarify deadline?

**Comment by roman-dubrovsky** [comment]
@nikitasakov no deadline

**Comment by nikitasakov** [comment]
I've created [topic](https://i.datarockets.com/t/datarockets-style-for-ruby-code/189) with info about datarockets-style.
