### ISSUE TITLE
Version backward compatibility and version number convention

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#28]
I have some issues with versions convention and should we added some needed version modifications to Readme, e.g ( gem 'datarockets-style', '~> 0.1.0' )

Also, we should remember that rubucop has not been released to the first version so they suggest using conservative version lock (see https://github.com/rubocop-hq/rubocop#installation )

First of all, I think we should re-read and remember about gem version modifications and then make any decisions. 

@AleksSenkou @dzhlobo do you have any thoughts?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I don't think that we can maintain backward compatibility, especially when we change rules. For example, in 0.1.1 your rubocop will be green but in 0.1.2 red. And it's fine for lint gem

I guess we can have milestones and the main difference between 0.1 and 0.2. For ex, 0.2 should include all possible rules configurations. 0.3 has ability to use rials/rspec/api groups and so on

Thoughts?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou no, I don't want to do this plan by reasons: 

1) There are special rules for versions (see https://semver.org/) so the patch versions we should use only for some bugs.

2) The main reason - I want to synchronize our versions with main rubocop library. So what do you think:

1) MAJOR VERSION -  synchronize with rubocop major version (when they release the first version we'll release it as well)  
2) MINOR - will use it for main changes (new cops, new features requests (which changes code style), upgrading dependencies  
3) PATCH -  fixes and patches (e.g.  style guide says one thing, but rubocop makes some mistake)

Thoughts?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky sounds good to me 👍 

Did you think about milestones for having a stable minor version with most of our rules applied?

**Comment by roman-dubrovsky** [comment]
yes, I'm doing it right now

**Comment by roman-dubrovsky** [comment]
@AleksSenkou https://github.com/datarockets/datarockets-style/milestone/1

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I see, looks great 👍 

Will you include other copes-related issues in the milestone? Issues like this one - https://github.com/datarockets/datarockets-style/issues/32

**Comment by roman-dubrovsky** [comment]
no, I don't want to add it to the current. Maybe on the next one

**Comment by AleksSenkou** [comment]
@roman-dubrovsky what is the separation? How do you measure what to include and what not to include?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou no any criteria. I'm just not sure that #32 is ready to implement and want to get some more thoughts. And I don't want to block release via this issue. 

Anyway, I don't have any processes how to create a list of issues.

**Comment by roman-dubrovsky** [comment]
usually, I have my own plan in my mind which is a base of milestone list. Then I just add issues which other datarockers want and can implement

**Comment by AleksSenkou** [comment]
Got it, I don't have an idea too.

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I like this one https://github.com/datarockets/datarockets-style/issues/28#issuecomment-511544115
