### ISSUE TITLE
Do not check subject and use `is_expected` instead of it (Rspec)

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#29]
The general rule looks like: do not use `expect(subject)` or `expect(subject_name` and use `is_expected` instead of it. 

```ruby
# first example - bad

subject { service.call }

it 'test' do
  expect(subject).to eq value
end  

# second example -  bad

subject(:service_call) { service.call }

it 'test' do
  expect(service_call).to eq value
end  

# third example - good

subject { service.call }

it 'test' do
  is_expected.to eq value
end  

# fourth example - also good

subject(:service_call) { service.call }

it 'test' do
  expect(service_call.valid?).to be true
end  

# fifth example - also good

subject(:service_call) { service.call }

it 'test' do
  expect { service_call }.to change { User.count }
end  
```

I can find only this cop https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecnamedsubject which restrict using `subject` in tests and ask to use the subject name or `is_expected` (so the second example is correct). Also, I couldn't find related issues with the question. 

So my question: 

- what do you think about this rule? Does the second example of sense?
- do you know some other issues or cops with this topic?

**Comment by roman-dubrovsky** [comment]
I found another rule. Looks like should not use `is_expected.to` into multiline tests. 

https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecimplicitsubject

so 

```ruby
# second example -  good (not bad)

subject(:service_call) { service.call }

it 'test' do
  expect(service_call).to eq value
end  

# third example - bad (not good)

subject { service.call }

it 'test' do
  is_expected.to eq value
end 
``` 

you thoughts?

**Comment by bibikovilya** [comment]
`is_expected` looks the pretty for one-line tests. It can make confusion in multiline tests. 
`subject` looks good when it represent the described class with simple `call` method.

**Comment by roman-dubrovsky** [comment]
> is_expected looks pretty for one-line tests. It can make confusion in multiline tests.


@bibikovilya and where big differences between these examples?

```ruby
it {  is_expected.to eq value }

# and

it "returns a correct value" do
  is_expected.to eq value
end
```

**Comment by bibikovilya** [comment]
> where big differences between these examples?

There is no difference between the examples. I mean when we have the other code besides `is_expected`.

**Comment by roman-dubrovsky** [comment]
@bibikovilya I can't imagine it for now but maybe it makes sense. So as a summary, you're agreed with current rubocop rules

**Comment by bibikovilya** [comment]
@roman-dubrovsky, not exactly. I think that 

```
subject { service.call }

it 'test' do
  is_expected.to eq value
end 
```

looks good without other code in `it` block. We can't check it via rubocop, I understand this. 
But I think we need to allow [the next code](https://github.com/JumpDEMAND/activedemand/pull/1845#discussion-diff-298966768L29) for tests.

**Comment by roman-dubrovsky** [comment]
My idea is that `RSpec/NamedSubject` should be required (so each subject should have a name), otherwise `RSpec/ImplicitSubject` should be disabled so that the developer can make a decision where it should and should not use `is_expected`

As a code style rule, we can use something like

### Using subjdct

Each subject should be named and we should not use `subject` in our test cases. Prefer to use `is_expected` that `expect(subject_name)` for small tests.

```ruby
# bad

subject { service.call }

it 'test' do
  expect(subject).to eq value
end  

# ok

subject(:service_call) { service.call }

it 'test' do
  expect(service_call).to eq value
end  

# better

subject { service.call }

it 'test' do
  is_expected.to eq value
end  

# good

subject(:service_call) { service.call }

it 'test' do
  expect(service_call.valid?).to be true
end  

# good

subject(:service_call) { service.call }

it 'test' do
  expect { service_call }.to change { User.count }
end
```
