### ISSUE TITLE
Style/Documentation

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#31]
Will we disable this cop? And when? Only for app and rspec directories? 

https://rubocop.readthedocs.io/en/latest/cops_style/#styledocumentation

**Comment by AleksSenkou** [comment]
I'd disable it. Documentation by default sucks, it's really not needed everywhere

**Comment by roman-dubrovsky** [comment]
@AleksSenkou @lazycoder9 my question was: should we disable this cop in all cases? E.g. we can add some documentation for utils from `lib` directories and rake tasks. Does it make sense?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky it doesn't 😄

**Comment by roman-dubrovsky** [comment]
@AleksSenkou any thoughts? why it doesn't?

**Comment by roman-dubrovsky** [comment]
also,  what about ruby gems?

**Comment by AleksSenkou** [comment]
> any thoughts? why it doesn't?

I believe we discussed it tones of times - code should document itself. Tests should document the behavior

If you want to document rack task usage - write clean code for that, else basic usage can be added to a project's README

**Comment by AleksSenkou** [comment]
> also, what about ruby gems?

@roman-dubrovsky the same pattern if it's possible to write clean code

**Comment by roman-dubrovsky** [comment]
> I believe we discussed it tones of times - code should document itself. Tests should document the behavior

no, we didn't discuss it tones of times cause I don't believe in the rule `code should document itself` / . Yep, I agree that this is a perfect rule but:

1) it doesn't exclude adding some documentation.
2) it works well only for cases when we have stable patterns and you don't need to think much about implementation stuff. + clean code and easy-for-understanding code aren't the same things (somebody can write a nice code with perfect design but it can be hard for understanding to you cause usually you're using another code style and patterns). And I really enjoy investigating this code base https://github.com/plataformatec/simple_form/blob/master/lib/simple_form/form_builder.rb#L47 ,

**Comment by roman-dubrovsky** [comment]
> If you want to document rack task usage - write clean code for that, else basic usage can be added to a project's README

@AleksSenkou are there big differents between README note and short documentation?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I don't mind using documentation if you want them so hot 😄 

I personally left comments only several times, because of hacky solutions I used. Leaving comments can be useful, but it's like an exception from the rule

> it works well only for cases when we have stable patterns

@roman-dubrovsky yeah, that's true. And it's really most of our cases.

-------------------------------------------------------

@roman-dubrovsky I saw the unreadable code and the worst I saw else - staled comments that only spoils understability. Again, for me, the rule is not to leave comments (with exception for tricky places).

**Comment by AleksSenkou** [comment]
> are there big differents between README note and short documentation?

@roman-dubrovsky yeah, I add comments about some common for the project rack task for developers to understand which to use for which cases. When you have 20+ tasks, then it's craziness to open most of them to find useful for you. README as an aggregation

**Comment by roman-dubrovsky** [comment]
> I personally left comments only several times, because of hacky solutions I used. Leaving comments can be useful, but it's like an exception from the rule

this is not just a comment but comments in the special format. 

> yeah, I add comments about some common for the project rack task to README for developers to understand which to use for which cases. When you have 20+ tasks, then it's craziness to open most of them to find useful for you. README as an aggregation

yes, it makes sense. But also, the documentation does not exclude notes in README

P.S. @AleksSenkou I freeze this issue for now cause want to concentrate on other things

**Comment by AleksSenkou** [comment]
> this is not just a comment but comments in the special format

@roman-dubrovsky is it possible to write rack tasks in special format instead of leaving comments in a special format?

> I freeze this issue for now cause want to concentrate on other things

Got it 👍

**Comment by roman-dubrovsky** [comment]
Ok, my proposal:

- for public libraries (ruby.yml) config, I'd like to male that cop required. I just want to say that this is really uncomfortable to investigate libraries w/o any docs. (What this method do? Why this model has been added) 

- no ides about Rails application. Probably, I'll exclude that cop for `app` directory cause most entities here have a stable and consistent structure. In other cases (like `lib` directory and rake tasks), I'd like to make that cop active cause in these cases module does not split by categories, have a random structure which makes harder supporting of that modules.

Thoughts?

**Comment by texpert** [comment]
Documentation is a good thing, if properly written. But I won't enable this cop, as a general rule, I'd let the author and code reviewers decide whether documentation is necessary. Except of the gems, where it should be required, IMO.

**Comment by roman-dubrovsky** [comment]
ok, we agreed that this rule should be enabled for ruby config (which we're using for ruby gem projects) 

For Rails projects, we're going to disable this cop but also we can add a note that we strongly recommend leaving some documentation for your classes and modules (especially for `lib` directory and custom test matchers). Correct? 

P.S. My personal opinion that we can disable this cop only for `app` directory cause here we have a most-less approved structure. But the variant above works for me too.

**Comment by texpert** [comment]
Yeah, @roman-dubrovsky , I think it is a good idea to disable this cop only for the `app` directory!
