### ISSUE TITLE
Disable RSpec/NestedGroups rule

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#36]
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecnestedgroups

What are your thoughts about this rule? Do we need to use it or not? I'm not really sure why this rule has been added but from my side looks like this cop can make tests a little bit readable but adds more duplications

**Comment by AleksSenkou** [comment]
This one is tricky 😄 

I like defining lets in related context blocks, otherwise why we need context block?
In most cases we have if/else logic covered by contexts so I haven't seen structure like:
```
context
  let

  context
    let

    context
      let
      it
```

Normally its:
```
context
  let

  context
    let
    it

  context
    let
    it
```

Not sure how to configure this rule better

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I can send you some examples if you want. Cause looks like this is a common case (especially for requests and capybara tests)

**Comment by AleksSenkou** [comment]
@roman-dubrovsky it will be appreciated cause maybe I'm missing something

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I just opened a first test file

```ruby
require "spec_helper"

describe EmailNotification::SendToContentAuthor do
  describe '#call' do
    context "when email notification is enable" do
      it "calls notifier for author"

      context 'when editor present' do
        it "calls notifier for editor"

        context 'when the editor is an author' do
          it 'sends notification only once'
        end
      end
    end

    context "when email notification is not enable" do
      it "does not call notifier"
    end
  end
end

```

**Comment by AleksSenkou** [comment]
@roman-dubrovsky looks good to me

**Comment by texpert** [comment]
Nested example groups are adding to readability, hinting the workflow, so I think it's better to turn this cop off.
