### ISSUE TITLE
Multiline method call

### ISSUE THREAD

**Issue by TheBlackArroVV** [datarockets/datarockets-style#39]
For now we use 
```ruby
def foo(bar,
  baz)
  123
end

def foo(
  bar,
  baz
)
  123
end
```
But i think, that
```ruby
def foo(bar,
        baz)
  123
end
```
is more readable.
What do you think?

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV can you give me some more realistic example? Cause I don't think that this is looking more clear or readable. 

First of all, this is a typical case. But let's imagine this method

```ruby
  def post_contact_with_opportunity(contact:, history:, owner_id:, user:, organization:,
    with_opportunity: false, opportunity_config: nil, include_leads: false)
    DynamicsUtil::PostContact.call(...)
  end
```

Otherwise, this a huge indentation makes me crazy and this is needed to use additional line

```ruby
  def post_contact_with_opportunity(contact:, history:, owner_id:, user:, organization:,
                                    with_opportunity: false, opportunity_config: nil, 
                                    include_leads: false)
    DynamicsUtil::PostContact.call(...)
  end
```

**Comment by TheBlackArroVV** [comment]
@roman-dubrovsky , your second example is what i mean. Yes, it takes additional line, but its looks more clear where arguments ends and starts method body

**Comment by roman-dubrovsky** [comment]
well, I just don't think so

**Comment by TheBlackArroVV** [comment]
So we need more thoughts about this

**Comment by AleksSenkou** [comment]
```ruby
def post_contact_with_opportunity(contact:, history:, owner_id:, user:, organization:,
                                  with_opportunity: false, opportunity_config: nil, 
                                  include_leads: false)
```
I see an issue with such kind of code ^

Example: you need to change method's name -> you need to change the indentation of all lines with params -> craziness 😄 

Looks like we won't have issues going with:
```ruby
def foo(bar,
  baz)
  123
end

def foo(
  bar,
  baz
)
  123
```

**Comment by TheBlackArroVV** [comment]
```ruby  
def post_contact_with_opportunity(contact:, history:, owner_id:, user:, organization:,
    with_opportunity: false, opportunity_config: nil, include_leads: false)
    DynamicsUtil::PostContact.call(...)
end
```
For this code you will be also need to change it when method name will change
And if we write
```ruby
def method(bar,
                   baz,
                   *params,
                   **kargs)
  123
end
```
All also will be good

**Comment by AleksSenkou** [comment]
@TheBlackArroVV let me explain it differently, looks like I didn't do it clear the previous time:

1. We have:
```ruby
def make_it(bar,
           baz,
           *params,
           **kargs)
  123
end
```
2. I'd like to rename `make_it` to `make_it_when_something`
```ruby
def make_it_when_something(bar,
                           baz,
                           *params,
                           **kargs)
  123
end
```

As you can see we had to change the indentation of all the params which sucks




-------------------------------------------------------

My vote is for something where we don't need to change params' indentation all the time

**Comment by roman-dubrovsky** [comment]
First of all, I think this issue related to #33 and #34 so I grouped it into one milestone. 

@TheBlackArroVV  And here, I just agreed with Aleks here. And this is an example from my last PR 

<img width="930" alt="Screen Shot 2019-07-10 at 3 40 49 PM" src="https://user-images.githubusercontent.com/7738063/60969897-6a110e00-a329-11e9-8094-bf837da00e87.png">

**Comment by roman-dubrovsky** [comment]
also, looks like on all projects where we had started to use dynamic indentations we returned to static indentations in some time (and this works not only for ruby)

P.S. I think guys from glassfrog still have nightmares with this 

```jsx
var GovMtgTensionEditorComponent = createReactClass({
  propTypes: {
    circleId:           PropTypes.number.isRequired,
    meetingId:          PropTypes.number.isRequired,
    agendaItemId:       PropTypes.number.isRequired,
    legacyAutocomplete: PropTypes.number.isRequired,
    agendaLabel:        PropTypes.string.isRequired,
    tensionId:          util.propTypes.id,
    meetingType:        PropTypes.string,
  },

  // ...
```

**Comment by roman-dubrovsky** [comment]
Also, if you don't line that the arguments and code have the same level, we just can make in bigger (e.g. 4)

```ruby
  def post_contact_with_opportunity(contact:, history:, owner_id:, user:, organization:,
      with_opportunity: false, opportunity_config: nil, include_leads: false)
    DynamicsUtil::PostContact.call(...)
  end
```

Thoughts?

**Comment by DDKatch** [comment]
Even if it is [not conventional way](https://github.com/rubocop-hq/ruby-style-guide#no-trailing-params-comma), In this case I prefer this variant:
```
  def post_contact_with_opportunity(
    contact:, 
    history:, 
    owner_id:, 
    user:, 
    organization:,
    with_opportunity: false,
    opportunity_config: nil,
    include_leads: false
  )
    DynamicsUtil::PostContact.call(...)
  end
```
you can easily :
1) change method's name
2) add/remove params
3) read it (definitely better than @roman-dubrovsky example, I think)

**Comment by AleksSenkou** [comment]
Are we able to make a decision here? @TheBlackArroVV do you think we need further discussions here? voting?

**Comment by TheBlackArroVV** [comment]
@AleksSenkou , looks like we can close this issue

**Comment by roman-dubrovsky** [comment]
@AleksSenkou @TheBlackArroVV any thoughts by this comment https://github.com/datarockets/datarockets-style/issues/39#issuecomment-510047033 ?

**Comment by roman-dubrovsky** [comment]
https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175

@DDKatch this variant makes sense to me but unfortunally it

**Comment by roman-dubrovsky** [comment]
no worries ☝️ this is a fucking github UI

**Comment by roman-dubrovsky** [comment]
https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175

@DDKatch it makes sense for me in some cases

**Comment by AleksSenkou** [comment]
I do prefer https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175 for that - it's clear. When in one-line it's hard to read params.

can be just personal feeling

**Comment by roman-dubrovsky** [comment]
https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175

@AleksSenkou @DDKatch how do you think: should we set up a custom cop for making this rule? Or adding some note to style guide with label `recommended` (it can be required cause we don't have a lint for this)

**Comment by AleksSenkou** [comment]
`recommended` is good for me. we can add a feature request issue for adding custom cop later

thoughts?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou yes, I think so. But I'm not still sure that this https://github.com/datarockets/datarockets-style/issues/39#issuecomment-511474175 should be restricted rule (anyway we can discuss it in the separate issue).

@AleksSenkou @DDKatch so can you create an issue for this item?

**Comment by AleksSenkou** [comment]
I will
