### ISSUE TITLE
Contribution rules

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#4]
For having a stable contribution process, we need to describe the rules of contribution and probably create a checklist with specific actions

Example - https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by roman-dubrovsky** [comment]
@AleksSenkou I think this example is better for this gem https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md and we can use it as the base. Does it make sense?

**Comment by roman-dubrovsky** [comment]
Also, `Other ways to contribute` part looks nice 

https://github.com/plataformatec/devise/blob/master/CONTRIBUTING.md#other-ways-to-contribute

**Comment by roman-dubrovsky** [comment]
@AleksSenkou looks like project automatization does not work well 🤔
