### ISSUE TITLE
Rescued exception variable name

### ISSUE THREAD

**Issue by lazycoder9** [datarockets/datarockets-style#41]
After getting a comment from @AleksSenkou in project PR, decided to clarify how we should handle this rule. From my side, having the self-explained variable name (error) is better than just one character variable name (e)
```ruby
# bad
begin
  # do something
rescue MyException => exception
  # do something
end

# good
begin
  # do something
rescue MyException => e
  # do something
end

# good
begin
  # do something
rescue MyException => _e
  # do something
end
```

**Comment by AleksSenkou** [comment]
The same for me. None one-symbols variables because they pull down readability

**Comment by DDKatch** [comment]
@lazycoder9 Am I missed something? I thought you're against single-letter variables, but look on the #good / #bad comments they're in opposite side to you.

**Comment by AleksSenkou** [comment]
Especially crazy thing when:
```ruby
{...}.each do |k, v|
end

[].each_with_index do |val, i|
```

We are novelists who write prose not cryptologists 😄

**Comment by lazycoder9** [comment]
@DDKatch Oh, examples are just from documentation) And I don't like them

**Comment by roman-dubrovsky** [comment]
@lazycoder9 can you send a link to documentation? Or to cop source code?

**Comment by TheBlackArroVV** [comment]
I believe, that some of them just don't need full names and very intuitive
Like
```ruby
rescue MyException => e
```

**Comment by lazycoder9** [comment]
@roman-dubrovsky https://rubocop.readthedocs.io/en/latest/cops_naming/#namingrescuedexceptionsvariablename here

**Comment by roman-dubrovsky** [comment]
so it makes sense for me. But in this case I have a question, how will we fix it?

- use `exception` or `error` as a variable for errors ? 
- just disable this rule?

**Comment by lazycoder9** [comment]
I propose to use one of error/exception as a variable
