### ISSUE TITLE
PR templates

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#48]
I think it can be related with #9 issue. 

Now I'm thinking about two types of templates:

1) New feature: 

so that people do not forget that we need update not only rubocop config, I want to add a PR template with next steps of todo list:

* change rubocop config (the rubocop should be ordered by alphabet)
* add a note to the style guide doc (should by group by subjects)
* add a note to the changelog file

2) Update dependencies (issue or PR, I'm not sure)

* update dependencies to the latest version
* investigate how it changes and affect our current styles and cops
* check the required ruby version

Thoughts? cc @AleksSenkou

**Comment by roman-dubrovsky** [comment]
P.s. for updating dependencies needs to add (update Gemfile.lock)

**Comment by AleksSenkou** [comment]
@roman-dubrovsky looks good to me

here are comments:
> change rubocop config (the rubocop should be ordered by alphabet)
`change rubocop config (the cops should be ordered by alphabet)` instead?

> add a note to the style guide doc (should by group by subjects)
`add a note to the style guide doc (should be grouped by subjects)`

**Comment by roman-dubrovsky** [comment]
@AleksSenkou thank you. But it was just MVP so I didn't worry much about grammar

**Comment by AleksSenkou** [comment]
@roman-dubrovsky got it. Sorry for being pedantic where not needed

**Comment by roman-dubrovsky** [comment]
@AleksSenkou np, I like it. This is just less work for the guy who'll resolve this issue
