### ISSUE TITLE
RSpec/SubjectStub cop

### ISSUE THREAD

**Issue by an-korn** [datarockets/datarockets-style#54]
Hey, guys, what do you think about this cop? Why should not we stub our subjects in tests? Because sometimes in tests we want to check whether subject receives some method, for example:
```ruby
subject(:client) { described_class.new(account.id) }

it 'refreshes access token' do
  expect(client).to receive(:refresh_token!)
  client.get(path)
end
```

https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecsubjectstub

**Comment by AleksSenkou** [comment]
Looks redundant for me too 👍 

I guess having methods stubbed with return value is just useful practice and is used in mostly all cases. But don't think it's mandatory

**Comment by roman-dubrovsky** [comment]
@an-korn @AleksSenkou I don't agree with you (including that I wrote this test 😄above ). 

First of all, can you say why and in which cases we should stub the private method of tested class?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky a case when stub doesn't need return value:

```ruby
describe Apps do
  subject(:apps) { Apps }

  describe '#all' do
    it 'returns wld, counter, daily activities, and book reading apps' do
      expect(Wld::App).to receive(:new).with(no_args).ordered
      expect(Counter::App).to receive(:new).with(no_args).ordered
      expect(DailyActivities::App).to receive(:new).with(no_args).ordered
      expect(BookReadings::App).to receive(:new).with(no_args).ordered

      apps.all
    end
  end
end

class Apps
  def self.all
    [Wld::App.new, Counter::App.new, DailyActivities::App.new, BookReadings::App.new]
  end
end
```

**Comment by AleksSenkou** [comment]
@roman-dubrovsky not sure that I understand why you ask for an example 😄 
Is it because of the stubbed private method in the example of the issue description?
If yes - should be stubbed class that called inside `refresh_token` method

**Comment by roman-dubrovsky** [comment]
@AleksSenkou ok, looks like you didn't understand the issue. Here we're stubbing a method of `subject` (tested object), in your example, you're stubbing other classes (and this looks nice)

**Comment by roman-dubrovsky** [comment]
so, it looks like

```ruby
def Client 
  def get(path)
    refresh_token!
    do_other_things
  end

  private
  
  def refresh_token!
    some_logic  
  end
end

describe '#get'
  subject(:client) { described_class.new(account.id) }

  it 'refreshes access token' do
    expect(client).to receive(:refresh_token!)
    client.get(path)
  end
end
```

**Comment by roman-dubrovsky** [comment]
@an-korn can you describe why we decided to stub private method?

**Comment by roman-dubrovsky** [comment]
@an-korn @AleksSenkou  Have I described why we shouldn't disable this metric on meetup? And can I close this issue?

**Comment by AleksSenkou** [comment]
@roman-dubrovsky yeah, sounds good to me

**Comment by an-korn** [comment]
@roman-dubrovsky yes, sure
