### ISSUE TITLE
Empty method style

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#56]
By default, the rubocop change empty method to the style above (and write it via single line)

```ruby
-  def send_notifications
-  end
+  def send_notifications; end
```

But I prefer to do it as two lines. So what do you think about this rule?

**Comment by roman-dubrovsky** [comment]
cop `Style/EmptyMethod`

**Comment by AleksSenkou** [comment]
I do like two lines too
