### ISSUE TITLE
Rspec: RSpec/LetSetup - not to use `let!` 

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#58]
[This cop](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecletsetup) does not allow to use`let!` for setting up test data. 

By documentation, it should be disabled by default but I caught this issue in the project.

```
spec/services/review_status/move_to_published_spec.rb:14:5: C: RSpec/LetSetup: Do not use let! for test setup.
    let!(:status) { create :review_status, workflow: workflow, status: :approved, created_by: user }
    ^^^^^^^^^^^^^
spec/services/review_status/move_to_published_spec.rb:34:7: C: RSpec/LetSetup: Do not use let! for test setup.
      let!(:status) { create :review_status, workflow: workflow, status: :pending, created_by: user }
      ^^^^^^^^^^^^^
```

Any thoughts? I didn't investigate why it was added to the default config so I don't have any thoughts now.

**Comment by AleksSenkou** [comment]
@roman-dubrovsky can we just disable it explicitly?

**Comment by roman-dubrovsky** [comment]
From another hand, betterrspec guide suggests using `let!` for setting up data http://www.betterspecs.org/#let

**Comment by roman-dubrovsky** [comment]
> can we just disable it explicitly?

@AleksSenkou I can agree on it as a temporary solution but also we need to understand why this cap has been added (it can detect some design issues like #54 )

**Comment by nikitasakov** [comment]
Read - `https://github.com/rubocop-hq/rubocop-rspec/issues/94`

I've just read холивар about this rule and here is summary:

This cop checks if you **create var** and **don't use it**:
```ruby
# bad

let!(:status) { create :review_status }

# good

let!(:status) { create :review_status }

it "..." do
  expect(status).to eq(1)
end
```

This rule think that if you don't want to use this var you should use `before`:

```ruby
# good

before { create(:widget) }

```
But looks like the most of people don't like this cop

![image](https://user-images.githubusercontent.com/32716983/73462409-d0748100-438c-11ea-9300-844480b715d9.png)

I've seen a lot of meaningful examples where it is useful to use `let!` instead of `before`, but developer of this cop and some guys think that this cop should be enabled by default. They believe that if this cop was added it was discussed enough. And if it merged - it is new rules. Kinda if we don't like it we should discuss it before merging. This issue closed and looks like this cop is going to live.

As I see there are no any design issues - it is kinda preference.

> From another hand, betterrspec guide suggests using let! for setting up data http://www.betterspecs.org/#let

@roman-dubrovsky in betterrspec guide they use `let` for creating but they use this var in `it`. It is the difference.

So I see 2 options:
- Close this issue and go with disabled cop. If we want to use `let!` instead of `before`. There are no any underwater rocks - it is just style.
- Revert PR with disabling of this cop and use `before` if we are not going to use var that we create in `let!`

What do you guys think about it?

**Comment by texpert** [comment]
I vote for 1st option.

**Comment by roman-dubrovsky** [comment]
@nikitasakov yep, I know it (I've investigated this issue before cause faced many times with it in the project), and I'm the person who agreed with that rule and vote for the second option (in fact for the third option and I don't think that we should revet commit instead of creating a new one)

**Comment by roman-dubrovsky** [comment]
ok, it seems like only I want to leave that cop and all other guys want to disable it, am I right? 😄

**Comment by texpert** [comment]
Yep, @roman-dubrovsky, just had a legit case of using `let!` in a spec last week.

**Comment by roman-dubrovsky** [comment]
@texpert JFYI, this cop is not about using `let!` at all (you still can use them).  This is about that we can use unreferenced `let!` (which we are not using in the tests and use only for setting up test data). 

See https://github.com/datarockets/datarockets-style/issues/58#issuecomment-580311391

```ruby
# bad

let!(:status) { create :review_status }

# good

let!(:status) { create :review_status }

it "..." do
  expect(status).to eq(1)
end
```

**Comment by texpert** [comment]
Exactly, @roman-dubrovsky :

```
  context 'when an address is found in the DB with these coordinates' do
    # rubocop: disable RSpec/LetSetup
    let!(:address) { create :address }
    let!(:latitude) { address.latitude }
    let!(:longitude) { address.longitude }
    # rubocop: enable RSpec/LetSetup

    it "doesn't create an Address" do
      expect { post_request }.not_to change(Address, :count)
    end
```

If `Address.create` would be used, there is risk of polluting the DB for other specs.

**Comment by roman-dubrovsky** [comment]
@texpert seems like this is not full test. What is `post_request`? and why do you need `latitude` and `longitude`?

**Comment by roman-dubrovsky** [comment]
Just most these cases, can be written as 

```ruby
context 'when an address is found in the DB with these coordinates' do
  before
    create :address, params
  end

  it "doesn't create an Address" do
    expect { post_request }.not_to change(Address, :count)
  end
end
```

but seems like we need to use  `latitude` and `longitude` somewhere 🤔 . And looks like we pass with variables on sending post request. So in this case, we just don't need to use `let!`

```ruby
  let(:post_request) { post '/address', address: {longitude: longitude, latitude: latitude} }

  context 'when an address is found in the DB with these coordinates' do
    let(:address) { create :address } # no need let!, cause this variable will be called before sending request
    let(:latitude) { address.latitude }
    let(:longitude) { address.longitude }

    it "doesn't create an Address" do
      expect { post_request }.not_to change(Address, :count)
    end
```

@texpert what do you think? 

P.S. but I can miss something cause don't see the full test file

**Comment by roman-dubrovsky** [comment]
@texpert oh, my bad. Got you point 😄

**Comment by roman-dubrovsky** [comment]
ok, let's disable this cop. of course, we can write something like this but this looks like a hack

```ruby
before do
  address
end
```

**Comment by roman-dubrovsky** [comment]
or like my first variant

```ruby
context 'when an address is found in the DB with these coordinates' do
  before
    create :address, latitude: latitude, longitude: longitude
  end

  it "doesn't create an Address" do
    expect { post_request }.not_to change(Address, :count)
  end
end
```

**Comment by roman-dubrovsky** [comment]
but looks like disabling this cop still better idea 🤔

**Comment by atatarenko** [comment]
I don't like messing with DB too much when writing unit tests and I use simple `let`s in 97% of cases so I'm for making this rule rather stricter than weaker. For that 3% left, I don't really care, I'm even okay if any kind of disabling cop comment would be used.

+1 for complaining about unreferenced `let!`s

P.S. We don't have `let!` on my current project and this is [the option](https://github.com/datarockets/datarockets-style/issues/58#issuecomment-586290727) which is usually used.

**Comment by roman-dubrovsky** [comment]
@texpert what do you think about code examples above?

Also,  if you don't have any agreements we can disable it by default and just add as a recommended cop? 

cc @atatarenko @lazycoder9 @AleksSenkou @nikitasakov

**Comment by texpert** [comment]
@roman-dubrovsky , I think it is not safe to create an entity in the before block. As I said earlier above - there is risk of polluting the DB for other specs. Doing it in a `let` or `let!` is ensuring it wouldn't leak into other contexts.

Anyway, thinking better of it, I agree with you and @atatarenko to enable this cop and to disable it when needed.

**Comment by roman-dubrovsky** [comment]
> I think it is not safe to create an entity in the before block

@texpert I amn't really clear how before the `before` block can affect other contexts?

**Comment by texpert** [comment]
@roman-dubrovsky , an AR instance created not in a `let` construct could somehow remain in the DB - I've seen such glitches.

**Comment by roman-dubrovsky** [comment]
@texpert will be cool if you'll sent them. Cause in my mind we should clean up database after each  test case and this variable should be created only for single context (as via `let!`, as via `before` block)

**Comment by texpert** [comment]
@roman-dubrovsky , I have retained no proof of it, but when the app is so big that it isn't using for specs any database_cleaner gem or transactional fixtures, the entities, created in `before` blocks are certainly not cleaned after each example, so `let` is safer. OK, giving it a good read, now I see that `let~` is just a wrap around a `before` block, so it isn't safe too in such a environment - which is explaining now to me why we couldn't get rid of flaky specs.
