### ISSUE TITLE
Add note with our DR rules

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#7]
* [x] https://github.com/roman-dubrovsky/datarockets-style/blob/master/default.yml
* [x] Describe it in the README

**Comment by roman-dubrovsky** [comment]
@AleksSenkou what about adding a separate md file (e.g. STYLEGUIDE.md) and describe our rule there

**Comment by AleksSenkou** [comment]
@roman-dubrovsky sounds good 👍 
So we can add a link to that from the main README
