### ISSUE TITLE
Braces around hash parameters

### ISSUE THREAD

**Issue by TheBlackArroVV** [datarockets/datarockets-style#73]
**Is your feature request related to a problem? Please describe.**
I think we should discuss this [cop](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/BracesAroundHashParameters).

**Additional context.**
My suggestion is:
```ruby
# bad

method({a: 'b'})

# good

method(a: 'b')
```

Your thoughts?

**Comment by roman-dubrovsky** [comment]
👍 , I think so

**Comment by roman-dubrovsky** [comment]
but your suggestions is default behavior for this cop, isn't it? https://rubocop.readthedocs.io/en/latest/cops_style/#stylebracesaroundhashparameters 

Or there are some problems with it?

**Comment by TheBlackArroVV** [comment]
Sure, but you commented on my pr, that we need to discuss it and you don't agree with my choice or i don't understand you well?

**Comment by roman-dubrovsky** [comment]
so I asked you about issues with cop and check the documentation better

The main issue here is a case when we pass more than one hash as arguments. And here we should have a question, does default variant works for us

```ruby
some_method(x, y, {a: 1, b: 2}, a: 1, b: 2)
```

So for this cop, I prefer to use `context_dependent` which looks better for my side in this case (also in this case, we do not use braces for single hash `method(a: 'b')` )

**Comment by roman-dubrovsky** [comment]
+ I'm agreed with some rule (which we want to change) we still need to discuss and add it to the shared config instead of saving it locally on the project config

**Comment by roman-dubrovsky** [comment]
does it make sense?

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV sorry, I didn't understand your comment above

**Comment by TheBlackArroVV** [comment]
@roman-dubrovsky , write method in which you want to provide this `some_method(x, y, {a: 1, b: 2}, a: 1, b: 2)` arguments

**Comment by TheBlackArroVV** [comment]
My fail, sorry

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV sorry, I still don't understand what do you want from me 😞

**Comment by TheBlackArroVV** [comment]
My point of view was, that we won't write methods, which get two different hash'es as params
But, as @roman-dubrovsky noticed, we already use rails, which have methods like [this](https://apidock.com/rails/ActionView/Helpers/FormTagHelper/select_tag#80-select-options-tag-no-more-worries-)
So i agree about context dependent style for this cop

**Comment by roman-dubrovsky** [comment]
@TheBlackArroVV yep, exactly. We won't write these methods but we'll use it (cause this is a usual interface for Rails and many old gems)
