### ISSUE TITLE
Allows adds additional files and directories to excluding block for rubocop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#80]
**Is your feature request related to a problem? Please describe.**

Now if you want to add a new file or directory to Exclude block for all cops, and try to write something like 

```yml
AllCops:
  Exclude:
    - "new file"
```

it overrides the current excluding list instead of extending it. Probably, we need to play with rubocop configurations for exclude rule. 

P.S. Also we can have similar issues for exclude block for other cops

**Comment by nikitasakov** [comment]
Just to clarify:
The problem is that when we add exclude in `rubocop.yml` file it overrides exclude inherited from `config/ruby.yml` and `config/rspec.yml`.
Correct me please if I am wrong
