### ISSUE TITLE
Think about bot which will check available versions of dependencies

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#83]
**Is your feature request related to a problem? Please describe.**

Now I just get email messages with all new releases. Think about automatization for this issue. E.g. https://github.com/marketplace/dependabot-preview

**Comment by roman-dubrovsky** [comment]
@ezhlobo can you as datarockets owner set up dependabot for this repo? Looks like I just don't have permissions for that.

**Comment by ezhlobo** [comment]
@roman-dubrovsky done. We should set it up. As far as I'm concerned we can do it in these two ways:

1) Add a configuration: https://dependabot.com/docs/config-file/
2) Do everything via their interface. You can sign in via github on app.dependabot.com, you should have an access.

If you'd like to go the second option and you don't have an ability to setup dependabot on your own, we can have a call and do that together ;).

**Comment by roman-dubrovsky** [comment]
@ezhlobo yep, let's do it

**Comment by ezhlobo** [comment]
@roman-dubrovsky so if you want to have a call to discuss that, schedule it and send me an invite ;).

**Comment by roman-dubrovsky** [comment]
done. @ezhlobo thank you ❤️
