### ISSUE TITLE
Allow use `for` with RSpec/ContextWording cop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#84]
**Is your feature request related to a problem? Please describe.**

For describing a great context description, better specs guide suggests us to use description which starts with `when` or `with` (+ rubocop extends this list with `without`).  

But after fixing this cop I found that prefix `for` is very popular in our team for describing a context. And I don't see any reasons not to use it including that it's some kind of quiet convention 

**Additional context.**

Example

```ruby
describe '#get_value' do
    context 'for not select value' do
      it 'returns value from object'
    end

    context 'for array based select' do
      it 'returns value from converted array'
    end

    context 'for hash based select' do
      it 'returns value from select hash' 
    end

    context 'for owner calculable type' do
      context 'when the user is found' do
        it { is_expected.to eq currenr_user.label }
      end

      context 'when the user is not found' do
        it { is_expected.to be nil }
      end
    end
  end
```

[Better specs rule](http://www.betterspecs.org/#contexts)
[Rubocop documentation](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspeccontextwording)

**Comment by AleksSenkou** [comment]
I do like `when` as a convention.

* It matches with tasks/cards naming. We have them starting with `When`
* Given-When-Then is a practice for bdd testing, exactly what we do

**Comment by AleksSenkou** [comment]
I'm not against `for` as well. Would go with both of them if wanted
