### ISSUE TITLE
Naming/MemoizedInstanceVariableName

### ISSUE THREAD

**Issue by lazycoder9** [datarockets/datarockets-style#85]
What do you think about this cop https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/MemoizedInstanceVariableName?

Should we use `@_foo` or `@foo` for memoized variables?

**Comment by roman-dubrovsky** [comment]
P.S. better doc https://rubocop.readthedocs.io/en/latest/cops_naming/#namingmemoizedinstancevariablename

**Comment by roman-dubrovsky** [comment]
> Should we use @_foo or @foo for memoized variables?

both works for me

**Comment by lazycoder9** [comment]
@AleksSenkou you've said to me, that you have convention to mark cached variables with `@_`. So, I think we should specify this in our style

**Comment by AleksSenkou** [comment]
How I see it: 
1) `@_foo` for a cashed copy of foo defined in `private` block
2) `@foo` for setting a public variable

**Comment by lazycoder9** [comment]
Will everyone agree to use this kind of convention?
```ruby
def foo
  @_foo ||= ...
end
```
