### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/datarockets-style#9]
For keeping issues and PRs structured, it worth having templates with questions and reminders in initial issue and PR bodies

* [ ] Discuss and create a template for an issue

**Comment by roman-dubrovsky** [comment]
I really love faker's templates https://github.com/stympy/faker/tree/master/.github/ISSUE_TEMPLATE

**Comment by roman-dubrovsky** [comment]
Also, I don't want to add PR templates.

**Comment by AleksSenkou** [comment]
@roman-dubrovsky sure, we can try to go without PR template and add it only if it will be needed. Removing from issue's description

**Comment by AleksSenkou** [comment]
@roman-dubrovsky thoughts about going without issue template as well?
we can have a process established at any time?

**Comment by roman-dubrovsky** [comment]
yep, makes sense

**Comment by AleksSenkou** [comment]
Closing. Can be reopened when makes sense
