### ISSUE TITLE
Do not add expectations into setup blocks

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#93]
**Is your feature request related to a problem? Please describe.**
Avoid using `expect` command into setup block. Cause the implementation can be changed and `expect` can be changed to `allow`. So I want to do it before this needs.

+ it breaks the next rule http://www.betterspecs.org/#single

**Additional context.**

Instead of 

```ruby
setup do
  expect(PipelineDealUtil::Debug).to receive(:call)
     .with(message: "clean attrs #{endpoint} => #{attributes_for_cleaning.inspect}",
          contact_id: contact.id, uid: uid)
end
```

write

```ruby
setup do
  allow(PipelineDealUtil::Debug).to receive(:call)
end

it 'test' do
  expect(PipelineDealUtil::Debug).to receive(:call)
       .with(message: "clean attrs #{endpoint} => #{attributes_for_cleaning.inspect}",
          contact_id: contact.id, uid: uid)
end
```

**Comment by an-korn** [comment]
@roman-dubrovsky ok, it seems to be reasonable for me.

**Comment by AleksSenkou** [comment]
Agree 100% and even more 😄 

Thank you for raising the issue!

**Comment by roman-dubrovsky** [comment]
https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecexpectinhook

**Comment by roman-dubrovsky** [comment]
P.S. The cop above works only with `before` block, but doesn't work with `setup` block.

`setup` - is a part of `rspec-rails` library https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/adapters.rb#L108

**Comment by roman-dubrovsky** [comment]
https://github.com/rubocop-hq/rubocop-rspec/issues/835

**Comment by roman-dubrovsky** [comment]
guys, what do you think about this issue. here, we have two solutions:

1) Add `setup` to Rspec rubocop dictionary, so that it can process it too. But here, but looks this is a feature of rubocop-rspec

https://github.com/rubocop-hq/rubocop-rspec/blob/9bce008e95154681945333e4a125013df43a3894/spec/rubocop/cop/rspec/hook_argument_spec.rb#L26-L30

2) Reject using 

```ruby
setup do
   # ...
end
```

and use this construction instead

```ruby
before do
  # ...
end
```

**Comment by texpert** [comment]
@roman-dubrovsky , I'd go with the 2nd.

**Comment by roman-dubrovsky** [comment]
@roman-dubrovsky  Comment here: https://github.com/rubocop-hq/rubocop-rspec/issues/835

**Comment by roman-dubrovsky** [comment]
Open new issue instead of this https://github.com/datarockets/datarockets-style/issues/219
