### ISSUE TITLE
RSpec/MessageSpies cop rule

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#94]
**Is your feature request related to a problem? Please describe.**
Here I just want to make a decision which rule will we use for [this cop](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecmessagespies).

1) Make call expectation after running test

 ```ruby
run_test
expect(foo).to have_received(:bar)
```

Pros:

* make expectation as for all tests after running so it can be more clear for developers
* looks like it also fixes the next issue https://github.com/datarockets/datarockets-style/issues/93
* default value for rubocop

2) Make expectations before running 

 ```ruby
expect(foo).to receive(:bar)
run_test
```

Pros:

* make this code consistent this method stubbing

```ruby
setup do
  allow(foo).to receive(:baz)
end

it 'test' do
  expect(foo).to receive(:bar)
  run_test
end
```

**Additional context.**

On the project, we're using the second variant and I'm going to leave the second variant for the project too (otherwise we need to spend much power for fixing this cop. We have more than 300 offenses in this case, and 0 if we leave the `receive` variant). Also, this is the main reasons why I know more cons for this item. 

Any thoughts? Cause looks like this cop just for voting

**Comment by an-korn** [comment]
@roman-dubrovsky seems to be the first approach is better to use, but I'd like to left the second variant for now.

**Comment by roman-dubrovsky** [comment]
> seems to be the first approach is better to use,

@an-korn can you print some words why? cause I don't have a confident position by this question

**Comment by an-korn** [comment]
@roman-dubrovsky according to [this](https://thoughtbot.com/blog/a-closer-look-at-test-spies) article the second approach is `more difficult to re-use, it breaks the linear readability of the Four-Phase test, and can lead to over-testing`

**Comment by roman-dubrovsky** [comment]
@an-korn according to this article the first AND second approach are more difficult to re-use and instead of spying method we should use mock object.

P.S. looks like also it describes cons for the first approach: it needs to duplicate mocking via `allow` operator. Bur for a good test, we still need doing it (so that we follow the rule: one test - one expectation   )

**Comment by roman-dubrovsky** [comment]
BTW, I'm going to add this issue to the current milestone and set up a secong rule by default

**Comment by AleksSenkou** [comment]
Guess it's more convenient to use 2. for unit testing (because of stubs), but the 1. for request testing (because of testing response and status)

Thoughts?

**Comment by roman-dubrovsky** [comment]
@AleksSenkou sorry,  I don't understand this point `for request testing (because of testing response and status)`? maybe some examples

**Comment by roman-dubrovsky** [comment]
ok, I'll change the first variant. Feel free to make a new issue if you want to change this rule
