### ISSUE TITLE
Rspec: RSpec/ExpectChange cop

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/datarockets-style#96]
**Is your feature request related to a problem? Please describe.**
I'd like to discuss this cop https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecexpectchange 

By default, this cop ask to pass class and method for method w/o arguments and use a block for method with arguments

```ruby
# good
expect { send_request }.to change(User, :count) 
expect { send_request }.to change { User.active.count }  
```

I'd like to change this value and make this cop consistent

```ruby
# good
expect { send_request }.to change { User.count }
expect { send_request }.to change { User.active.count }  
```

Thoughts?

**Comment by AleksSenkou** [comment]
I do like it, block usage is felt better here, btw use it all the time
